### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by raman325** [enriqg9/dual-thermostat#12]
Hi,

First off I love this card! Thanks for making it 😄 

Do you accept PRs? I've got some feature requests, and I'm willing to make these changes and submit them if you think they'd be worthwhile:

- Support for 0.96.0: per the [release notes](https://www.home-assistant.io/blog/#climate), two changes impact this card; `operation_mode` has been changed to `hvac_mode` and `auto` has now been split into `auto` and `heat_cool`
- Not sure if this came with 0.96.0 or if it was introduced earlier, but the thermostat component now supports low and high temperature setpoints, so I'd like to convert my two entities into one while still using this component.
- A new optional configuration option called `always_use_range_slider` (defaults to `false`) which uses the `range` sliderType for `heat`, `cool`, and `auto` when set to `true`. My use case is that my thermostat seems to forget that it has an `auto` mode after some time, so I have automation in place to switch between `heat` and `cool` as needed but I manage the temperatures as if it was `auto`

What do you think?

**Comment by enriqg9** [comment]
Thanks, I'm yet to update to 0.96 will update this weekend and review your PR.

**Comment by enriqg9** [comment]
Added support for Hass 0.96 https://github.com/enriqg9/dual-thermostat/commit/5887329679977e0178b263212c16106712f8bb89
