### ISSUE TITLE
Card does not work on .96

### ISSUE THREAD

**Issue by Chaotic** [enriqg9/dual-thermostat#14]
Updated to HA 0.96 and this card doesn't load.  I don't get an error that the custom element doesn't exist there is just nothing where it should be.

Nothing in my config changed between 0.95.2 (I think I went from .2) to 0.96

I see in the community thread that you are aware there is some issue so just opening an issue to track it.

**Comment by enriqg9** [comment]
Added support for Hass 0.96 https://github.com/enriqg9/dual-thermostat/commit/5887329679977e0178b263212c16106712f8bb89. There is a bug with Hass climate component, some modes do not work on 0.96 see https://github.com/home-assistant/home-assistant/issues/25322 there is a pending PR into Hass.
