### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by jccshmny** [enriqg9/dual-thermostat#16]
Card shows red with "Custom element doesn't exist: dual-thermostat".  

Errors in home-assistant.log show:

> https://xxx.ui.nabu.casa/local/dual-thermostat.js?v=1.1:7:1 Uncaught SyntaxError: Unexpected token <

F12 dev-tools show:

> Uncaught SyntaxError: Unexpected token <; dual-thermostat.js?v=1.1:7

**Comment by jccshmny** [comment]
Bump?

**Comment by enriqg9** [comment]
What home assistant version are you using?

**Comment by jccshmny** [comment]
0.97.2

**Comment by enriqg9** [comment]
I'm still on 0.96 will update and try to replicate.

**Comment by enriqg9** [comment]
Updated to 0.98.4 and working fine. Can't reproduce.
