### ISSUE TITLE
bottom cut off of card

### ISSUE THREAD

**Issue by typhoonss92** [enriqg9/dual-thermostat#2]
I noticed once in a while once the new ios app came out that the bottom of the card would be cut off and could not see the temp or the icons but could see the circular slider and the set temp. Once the new update 86/86.1 came out yesterday both the ios app and my chrome browser on my windows pc are doing this. But on the chrome browser on the pc the card looks like the normal size just the temp and icons are pushed down and can barely see the temp and there is just a white space where they should be. I have a HD fire tablet that I am running fully kiosk browser on and prior to the 86 update it would not show the card just an error but now it shows it just the way it is suppose to. Just seems like some kind of spacing issue. I attached a pic of the chrome browser on my pc for the card so you have an idea what it is doing. I also downloaded today and updated the .js for this and rebooted the hassio. 
Have you seen this happening? Not a big deal but something that just looked out of the ordinary.
Thanks in advance.
![dual-therm](https://user-images.githubusercontent.com/14281675/51705937-fc775c80-1fea-11e9-9ce5-ffbfcc3256d4.PNG)

**Comment by typhoonss92** [comment]
quick update, in the ios app if I turn the phone sideways it shows correctly.

**Comment by enriqg9** [comment]
Does this happen on your browser as well? Sorry don't have an iphone to reproduce.. Android user..

**Comment by enriqg9** [comment]
Fixed with [e82d2ec](https://github.com/enriqg9/dual-thermostat/commit/e82d2ec863d78414422cd0bea8ce1563959b069f).
