### ISSUE TITLE
Heat and cool buttons both start aircon

### ISSUE THREAD

**Issue by drclong** [enriqg9/dual-thermostat#20]
Setup as below on 0.97.1

type: 'custom:dual-thermostat'
name: Living
entities:
  - entity: climate.lounge_ac
    type: cool
  - entity: climate.lounge
    type: heat
fan_control: false
min_slider: 16
max_slider: 24

Slider settings are degrees C
Unexpected behaviour is that both the cooling and heating buttons both activate the lounge AC only.

![image](https://user-images.githubusercontent.com/19884789/67153193-7f3a0780-f330-11e9-86ac-27503494b757.png)

**Comment by enriqg9** [comment]
Is your entity a Z-wave thermostat?

**Comment by drclong** [comment]
No. One is just an [HA Generic Thermostat](https://www.home-assistant.io/integrations/generic_thermostat/) and the other is a [SmartIR](https://community.home-assistant.io/t/smartir-control-your-climate-tv-and-fan-devices-via-ir-rf-controllers/100798) thermostat controlling a Mitsubishi reverse cycle aircon.

**Comment by enriqg9** [comment]
This card is for Z-Wave thermostats that define two entities with one thermostat.
