### ISSUE TITLE
Support multiple presets in addition to multiple modes

### ISSUE THREAD

**Issue by matejdro** [enriqg9/dual-thermostat#24]
It seems like this card mostly work on thermostat that have multiple modes (such as cool, heat etc.)

However, my thermostat only has one mode (heat), but it has multiple presets:

![image](https://user-images.githubusercontent.com/507922/69485282-90010000-0e3d-11ea-9a7c-75cbf41fbd20.png)

It seems like dual thermostat does not recognize that and only displays single thermostat instead of dual one. So even when I have dual thermostat set up to display both entities

```
entities:
    - climate.radiator_dnevna_eco
    -  climate.radiator_dnevna
```

it appears that dual thermostat will not display dual slider, since thermostat is in heat mode.

Any chance you can an option to force display sliders for both entities, regardless of the selected mode?

**Comment by enriqg9** [comment]
The card renders the modes from the hvac_modes just like the native lovelace card does. The only modes supported by HASS are auto, heat_cool, heat, off, fan_only and dry.

**Comment by matejdro** [comment]
Yes, but my point is that two slider knobs are only displayed when `heat_cool` mode is selected. It would be helpful to have an option to always display two knobs.

**Comment by enriqg9** [comment]
The knob with the lower value controls the heating entity and the knob upper value controls the cooling entity. Why would you want to display two knobs if your entity does not have a cooling mode?

**Comment by matejdro** [comment]
I have two entities that represent two different presets:

* Regular heat mode (used when I'm home)
* Eco heat mode (used for when I'm not at home)

I would like to display both in the same thermostat.
