### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by northrup** [enriqg9/dual-thermostat#27]
After upgrading to Home-Assistant `0.103` any page that had the `dual-thermostat` card in the the Lovelace UI would not load. The error message given by the browser (Chrome, Safari, and Firefox) was:
```
In Chrome: 
Uncaught (in promise) TypeError:Cannot read property 'attributes' of null
```

```
In Safari:
Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'this.stateObj.attributes')
```

The only thing that has changed in my configuration is upgrading to `0.103` and restarting.

**Comment by enriqg9** [comment]
HA 0.103 changed the Z-Wave thermostat component, HA now defines only one entity for the Z-Wave thermostats thus this card is no longer needed. Use the native card instead. Check your entities and you should only have one.
