### ISSUE TITLE
Invalid Entity for latest HomeAssistant build

### ISSUE THREAD

**Issue by Knoxie** [enriqg9/dual-thermostat#28]
Home Assistant 0.103.2

`Developer Tools
https://www.knoxie89.duckdns.org/local/dual-thermostat/dual-thermostat.js?v=1:221:2363 Uncaught Error: Invalid entity.
9:17 AM components/system_log/__init__.py (ERROR) - message first occurred at 9:16 AM and shows up 4 times
http://192.168.0.111:8123/local/dual-thermostat/dual-thermostat.js?v=1:221:2363 Uncaught Error: Invalid entity.
8:56 AM components/system_log/__init__.py (ERROR)`

**Comment by enriqg9** [comment]
See #27

**Comment by Knoxie** [comment]
![image](https://user-images.githubusercontent.com/1057404/71202696-b9f5e880-226a-11ea-8f0d-e3e23f7c7360.png)

I'm still showing two separate entities?
