### ISSUE TITLE
Cannot get this thermostat in lovelace 

### ISSUE THREAD

**Issue by branitelj91** [enriqg9/dual-thermostat#29]
Good day. 
Being a total rookie in the HASSIO I am "struggling" with this. 
On that note I cannot get this thermostat in lovelace no matter what I have tried. 

I have followed instructions in readme still, no luck. 

I would appreciate any direction with help in this
Thanks

**Comment by enriqg9** [comment]
What version of HA are you on?

**Comment by branitelj91** [comment]
RPI 3, newest one hassio

**Comment by enriqg9** [comment]
See #27, will update Readme.
