### ISSUE TITLE
Unable to install with HACS (New Custom Updater)

### ISSUE THREAD

**Issue by kethoth** [enriqg9/dual-thermostat#7]
Please restructure this repo to function with [HACS](https://github.com/custom-components/hacs)

**Comment by enriqg9** [comment]
Won't be adding support for HACS.

**Comment by walthowd** [comment]
Another vote to add support HACS

**Comment by walthowd** [comment]
@enriqg9 I should add you don't need to change anything or restructure the directory or file names to support HACS -- just need to file a PR against HACS to add the repo

**Comment by enriqg9** [comment]
@walthowd I think it should be supported already? There was a merged PR adding support.

**Comment by walthowd** [comment]
@enriqg9 Yes, it is supported, but you would have to file a small pull requests against HACS to add it to the default repository. Per their policy they want these to be filed by the principal developer. See here for an example:

https://github.com/custom-components/hacs/pulls?q=is%3Apr+is%3Aclosed

**Comment by enriqg9** [comment]
Sent PR today.

**Comment by walthowd** [comment]
Thanks!
