### ISSUE TITLE
Doesn't load card

### ISSUE THREAD

**Issue by 3ative** [enriqg9/dual-thermostat#8]
* Installed in: www>dual-thermostat>dual-thermostat.js
* Lines added to resources:
` - type: js`
**and**
`/local/dual-thermostat/dual-thermostat.js?v=1`
* HA version - 0.94.3

But card just says: ***"Custom element doesn't exist: dual-thermostat."***

**Comment by enriqg9** [comment]
Can you share your entire YAML file

**Comment by 3ative** [comment]
@enriqg9 thanks for the reply... Sadly after many attempts and config changes, I removed everything. :(

**Comment by 3ative** [comment]
Should I try again and post an update?

**Comment by 3ative** [comment]
Oh, you closed this.. ok
